import { defineCollection } from "astro:content";
import { docsLoader, i18nLoader } from "@astrojs/starlight/loaders";
import { docsSchema, i18nSchema } from "@astrojs/starlight/schema";
import { z } from "astro/zod";

const customI18nSchema = z.object({
  landing: z.object({
    gettingStarted: z.string().optional(),
    title: z.string().optional(),
    subtitle: z.string().optional(),
    description: z.string().optional(),
    scrollDown: z.string().optional(),
    featuresTitle: z.string().optional(),
    plugAndPlayTitle: z.string().optional(),
    plugAndPlayDesc: z.string().optional(),
    deferredTitle: z.string().optional(),
    deferredDesc: z.string().optional(),
    forwardTitle: z.string().optional(),
    forwardDesc: z.string().optional(),
    ctaTitle: z.string().optional(),
    ctaSubtitle: z.string().optional(),
    nodeDemoDeferred: z.string().optional(),
    nodeDemoForward: z.string().optional(),
    copyHint: z.string().optional(),
    learnMore: z.string().optional(),
    faqTitle: z.string().optional(),
    faqQ1: z.string().optional(),
    faqA1: z.string().optional(),
    faqQ2: z.string().optional(),
    faqA2: z.string().optional(),
    faqQ3: z.string().optional(),
    faqA3: z.string().optional(),
    faqQ4: z.string().optional(),
    faqA4: z.string().optional(),
    faqQ5: z.string().optional(),
    faqA5: z.string().optional(),
    deferredFeature1: z.string().optional(),
    deferredFeature2: z.string().optional(),
    deferredFeature3: z.string().optional(),
    deferredFeature3New: z.string().optional(),
    deferredStylesTitle: z.string().optional(),
    deferredStylesDesc: z.string().optional(),
    style1Name: z.string().optional(),
    style1Desc: z.string().optional(),
    style2Name: z.string().optional(),
    style2Desc: z.string().optional(),
    style3Name: z.string().optional(),
    style3Desc: z.string().optional(),
    style4Name: z.string().optional(),
    style4Desc: z.string().optional(),
    customBxdfTitle: z.string().optional(),
    customBxdfDesc: z.string().optional(),
    forwardFeature1: z.string().optional(),
    forwardFeature2: z.string().optional(),
    forwardFeature3: z.string().optional(),
    comingSoon: z.string().optional(),
    footerBranding: z.string().optional(),
    fabStore: z.string().optional(),
    deferredSectionTitle: z.string().optional(),
    forwardSectionTitle: z.string().optional(),
    navDeferred: z.string().optional(),
    navForward: z.string().optional(),
    navMobile: z.string().optional(),
    mobileSectionTitle: z.string().optional(),
    mobileTitle: z.string().optional(),
    mobileDesc: z.string().optional(),
    mobileDownloadHint: z.string().optional(),
    android: z.string().optional(),
    vr: z.string().optional(),
    ios: z.string().optional(),
    viewDocs: z.string().optional(),
  }).optional(),
  Uebp: z.object({
    copy: z.string().optional(),
  }).optional(),
});

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
  i18n: defineCollection({
    loader: i18nLoader(),
    schema: i18nSchema({ extend: customI18nSchema }),
  }),
};
